name: Python Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
        architecture: [x86]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -VV
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Run linter
      run: |
        flake8
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
